#[derive(Debug, Clone, Copy)]
pub struct CommandSchema {
    pub id: &'static str,
    pub title: &'static str,
    pub resource: &'static str,
    pub operation: &'static str,
    pub command: &'static str,
    pub status: &'static str,
    pub aliases: &'static [&'static str],
    pub http: &'static [&'static str],
    pub auth_required: bool,
    pub dry_run: bool,
    pub confirmation_required: bool,
    pub compact: bool,
    pub notes: Option<&'static str>,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ListOptions<'a> {
    pub compact: bool,
    pub resource: Option<&'a str>,
    pub operation: Option<&'a str>,
    pub status: Option<&'a str>,
}

pub const COMMAND_SCHEMAS: &[CommandSchema] = &[
    CommandSchema {
        id: "auth.login",
        title: "Browser or manual cookie login",
        resource: "auth",
        operation: "auth",
        command: "dida auth login --browser --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Stores only the Dida365 t cookie under the local config directory."),
    },
    CommandSchema {
        id: "auth.status",
        title: "Check local auth",
        resource: "auth",
        operation: "read",
        command: "dida auth status --verify --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "doctor",
        title: "Check CLI, config, auth, and optional endpoint health",
        resource: "system",
        operation: "read",
        command: "dida doctor --verify --json",
        aliases: &[],
        http: &["GET /batch/check/0 when --verify is set"],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Without --verify this command is local-only and reports network_check: not_run.",
        ),
    },
    CommandSchema {
        id: "schema.list",
        title: "List local command contracts",
        resource: "schema",
        operation: "read",
        command: "dida schema list --compact --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "Local-only command index. Use schema show for full details, HTTP surfaces, and notes.",
        ),
    },
    CommandSchema {
        id: "schema.show",
        title: "Show one local command contract",
        resource: "schema",
        operation: "read",
        command: "dida schema show <schema-id> --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Local-only detailed schema for one command."),
    },
    CommandSchema {
        id: "channel.list",
        title: "Explain API channel selection and auth boundaries",
        resource: "channel",
        operation: "read",
        command: "dida channel list --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Local-only guide for choosing Web API, Official MCP, or Official OpenAPI without mixing auth models.",
        ),
    },
    CommandSchema {
        id: "official.doctor",
        title: "Check official dida365 MCP channel",
        resource: "official",
        operation: "read",
        command: "dida official doctor --json",
        aliases: &[],
        http: &[
            "POST https://mcp.dida365.com initialize",
            "POST https://mcp.dida365.com tools/list",
        ],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.tokenStatus",
        title: "Check saved official MCP token config",
        resource: "official",
        operation: "auth",
        command: "dida official token status --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Reports whether DIDA365_TOKEN or saved local token config is available without printing the full token.",
        ),
    },
    CommandSchema {
        id: "official.tokenSet",
        title: "Save official MCP token config",
        resource: "official",
        operation: "auth",
        command: "dida official token set --token-stdin --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Stores the official MCP token locally. DIDA365_TOKEN still takes precedence."),
    },
    CommandSchema {
        id: "official.tokenClear",
        title: "Clear saved official MCP token config",
        resource: "official",
        operation: "auth",
        command: "dida official token clear --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "official.tools",
        title: "List official dida365 MCP tools",
        resource: "official",
        operation: "read",
        command: "dida official tools --limit 100 --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/list"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config. Default output is compact; use --full for raw schemas.",
        ),
    },
    CommandSchema {
        id: "official.show",
        title: "Show official dida365 MCP tool schema",
        resource: "official",
        operation: "read",
        command: "dida official show <tool-name> --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/list"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.call",
        title: "Call an official dida365 MCP tool",
        resource: "official",
        operation: "write",
        command: "dida official call <tool-name> --args-json '{...}' --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config. Prefer read-only exploration; write-capable tools have no dry-run here, so use first-class wrappers or explicit operator approval.",
        ),
    },
    CommandSchema {
        id: "official.project.list",
        title: "List projects through official MCP",
        resource: "official-project",
        operation: "read",
        command: "dida official project list --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call list_projects"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.project.get",
        title: "Read one project through official MCP",
        resource: "official-project",
        operation: "read",
        command: "dida official project get <project-id> --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call get_project_by_id"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.project.data",
        title: "Read project and undone tasks through official MCP",
        resource: "official-project",
        operation: "read",
        command: "dida official project data <project-id> --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call get_project_with_undone_tasks"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.task.get",
        title: "Read one task through official MCP",
        resource: "official-task",
        operation: "read",
        command: "dida official task get <task-id> --project <project-id> --json",
        aliases: &[],
        http: &[
            "POST https://mcp.dida365.com tools/call get_task_by_id",
            "POST https://mcp.dida365.com tools/call get_task_in_project when --project is set",
        ],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.task.search",
        title: "Search tasks through official MCP",
        resource: "official-task",
        operation: "read",
        command: "dida official task search --query <text> --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call search_task"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.task.query",
        title: "List undone tasks through official MCP time query",
        resource: "official-task",
        operation: "read",
        command: "dida official task query --query today --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call list_undone_tasks_by_time_query"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config. Sends the query as query_command to the upstream MCP tool.",
        ),
    },
    CommandSchema {
        id: "official.task.undone",
        title: "List undone tasks by date through official MCP",
        resource: "official-task",
        operation: "read",
        command: "dida official task undone --start RFC3339 --end RFC3339 --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call list_undone_tasks_by_date"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.task.filter",
        title: "Filter tasks through official MCP",
        resource: "official-task",
        operation: "read",
        command: "dida official task filter --project <project-id> --status 0 --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call filter_tasks"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.task.batchAdd",
        title: "Batch add tasks through official MCP",
        resource: "official-task",
        operation: "write",
        command: "dida official task batch-add --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call batch_add_tasks"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config unless --dry-run is used. Payload follows the upstream MCP tool schema.",
        ),
    },
    CommandSchema {
        id: "official.task.batchUpdate",
        title: "Batch update tasks through official MCP",
        resource: "official-task",
        operation: "write",
        command: "dida official task batch-update --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call batch_update_tasks"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config unless --dry-run is used. Payload follows the upstream MCP tool schema.",
        ),
    },
    CommandSchema {
        id: "official.task.completeProject",
        title: "Complete tasks in one project through official MCP",
        resource: "official-task",
        operation: "write",
        command: "dida official task complete-project --project <project-id> --task <task-id> --dry-run --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call complete_tasks_in_project"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config unless --dry-run is used. Supports repeated --task or comma-separated --tasks.",
        ),
    },
    CommandSchema {
        id: "official.habit.list",
        title: "List habits through official MCP",
        resource: "official-habit",
        operation: "read",
        command: "dida official habit list --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call list_habits"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.habit.sections",
        title: "List habit sections through official MCP",
        resource: "official-habit",
        operation: "read",
        command: "dida official habit sections --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call list_habit_sections"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.habit.get",
        title: "Read one habit through official MCP",
        resource: "official-habit",
        operation: "read",
        command: "dida official habit get <habit-id> --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call get_habit"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.habit.create",
        title: "Create habit through official MCP",
        resource: "official-habit",
        operation: "write",
        command: "dida official habit create --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call create_habit"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config unless --dry-run is used. Payload follows the official MCP tool schema.",
        ),
    },
    CommandSchema {
        id: "official.habit.update",
        title: "Update habit through official MCP",
        resource: "official-habit",
        operation: "write",
        command: "dida official habit update <habit-id> --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call update_habit"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config unless --dry-run is used. Payload follows the official MCP tool schema.",
        ),
    },
    CommandSchema {
        id: "official.habit.checkin",
        title: "Upsert a habit check-in through official MCP",
        resource: "official-habit",
        operation: "write",
        command: "dida official habit checkin <habit-id> --date YYYY-MM-DD --value 1 --dry-run --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call upsert_habit_checkins"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config unless --dry-run is used.",
        ),
    },
    CommandSchema {
        id: "official.habit.checkins",
        title: "Read habit check-ins through official MCP",
        resource: "official-habit",
        operation: "read",
        command: "dida official habit checkins --habit-ids <ids> --from YYYYMMDD --to YYYYMMDD --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call get_habit_checkins"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires DIDA365_TOKEN or saved local official token config."),
    },
    CommandSchema {
        id: "official.focus.get",
        title: "Read one focus record through official MCP",
        resource: "official-focus",
        operation: "read",
        command: "dida official focus get <focus-id> --type 0|1 --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call get_focus"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config. Type 0 is Pomodoro; type 1 is timing.",
        ),
    },
    CommandSchema {
        id: "official.focus.list",
        title: "List focus records through official MCP",
        resource: "official-focus",
        operation: "read",
        command: "dida official focus list --from-time RFC3339 --to-time RFC3339 --type 0|1 --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call get_focuses_by_time"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config. Type 0 is Pomodoro; type 1 is timing.",
        ),
    },
    CommandSchema {
        id: "official.focus.delete",
        title: "Delete focus record through official MCP",
        resource: "official-focus",
        operation: "delete",
        command: "dida official focus delete <focus-id> --type 0|1 --yes --dry-run --json",
        aliases: &[],
        http: &["POST https://mcp.dida365.com tools/call delete_focus"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: Some(
            "Requires DIDA365_TOKEN or saved local official token config unless --dry-run is used. Use only when the target focus record is known.",
        ),
    },
    CommandSchema {
        id: "openapi.doctor",
        title: "Check official OAuth OpenAPI setup",
        resource: "openapi",
        operation: "read",
        command: "dida openapi doctor --json",
        aliases: &[],
        http: &["GET/POST oauth metadata only"],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Uses DIDA365_OPENAPI_CLIENT_ID / DIDA365_OPENAPI_CLIENT_SECRET or saved local client config.",
        ),
    },
    CommandSchema {
        id: "openapi.clientStatus",
        title: "Check saved official OpenAPI client config",
        resource: "openapi",
        operation: "read",
        command: "dida openapi client status --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Reports whether local OpenAPI client config is available without printing the secret.",
        ),
    },
    CommandSchema {
        id: "openapi.clientSet",
        title: "Save official OpenAPI client config",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi client set --id <client-id> --secret-stdin --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Stores client id and client secret locally for OAuth commands. Environment variables still take precedence.",
        ),
    },
    CommandSchema {
        id: "openapi.clientClear",
        title: "Clear saved official OpenAPI client config",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi client clear --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "openapi.status",
        title: "Check saved official OpenAPI OAuth token",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi status --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Reports whether a local OAuth access token is available without printing it."),
    },
    CommandSchema {
        id: "openapi.authUrl",
        title: "Generate official OpenAPI authorization URL",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi auth-url --json",
        aliases: &[],
        http: &["GET https://dida365.com/oauth/authorize"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "openapi.listenCallback",
        title: "Listen for one official OpenAPI OAuth callback",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi listen-callback --json",
        aliases: &[],
        http: &["GET local callback /callback?code=...&state=..."],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Local-only helper for manual no-browser OAuth flows."),
    },
    CommandSchema {
        id: "openapi.exchangeCode",
        title: "Exchange OAuth authorization code for access token",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi exchange-code --code <code> --json",
        aliases: &[],
        http: &["POST https://dida365.com/oauth/token"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "openapi.login",
        title: "Complete browser-based official OpenAPI OAuth login",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi login --browser --json",
        aliases: &[],
        http: &[
            "GET https://dida365.com/oauth/authorize",
            "GET local callback /callback",
            "POST https://dida365.com/oauth/token",
        ],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires client config and a developer app redirect URL matching the reported local callback.",
        ),
    },
    CommandSchema {
        id: "openapi.logout",
        title: "Clear saved official OpenAPI OAuth token",
        resource: "openapi",
        operation: "auth",
        command: "dida openapi logout --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Removes the saved local OpenAPI access token."),
    },
    CommandSchema {
        id: "openapi.projectList",
        title: "List projects through official OpenAPI",
        resource: "openapi",
        operation: "read",
        command: "dida openapi project list --json",
        aliases: &[],
        http: &["GET /open/v1/project"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.projectGet",
        title: "Get project through official OpenAPI",
        resource: "openapi",
        operation: "read",
        command: "dida openapi project get <project-id> --json",
        aliases: &[],
        http: &["GET /open/v1/project/{projectId}"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.projectData",
        title: "Get project data through official OpenAPI",
        resource: "openapi",
        operation: "read",
        command: "dida openapi project data <project-id> --json",
        aliases: &[],
        http: &["GET /open/v1/project/{projectId}/data"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token. Project id may be inbox."),
    },
    CommandSchema {
        id: "openapi.projectCreate",
        title: "Create project through official OpenAPI",
        resource: "openapi-project",
        operation: "write",
        command: "dida openapi project create --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/project"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token unless --dry-run is used."),
    },
    CommandSchema {
        id: "openapi.projectUpdate",
        title: "Update project through official OpenAPI",
        resource: "openapi-project",
        operation: "write",
        command: "dida openapi project update <project-id> --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/project/{projectId}"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token unless --dry-run is used."),
    },
    CommandSchema {
        id: "openapi.projectDelete",
        title: "Delete project through official OpenAPI",
        resource: "openapi-project",
        operation: "delete",
        command: "dida openapi project delete <project-id> --dry-run --yes --json",
        aliases: &[],
        http: &["DELETE /open/v1/project/{projectId}"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: Some("Requires an already saved OAuth access token. Preview with --dry-run first."),
    },
    CommandSchema {
        id: "openapi.taskGet",
        title: "Get task through official OpenAPI",
        resource: "openapi-task",
        operation: "read",
        command: "dida openapi task get --project <project-id> --task <task-id> --json",
        aliases: &[],
        http: &["GET /open/v1/project/{projectId}/task/{taskId}"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.taskCreate",
        title: "Create task through official OpenAPI",
        resource: "openapi-task",
        operation: "write",
        command: "dida openapi task create --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/task"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.taskUpdate",
        title: "Update task through official OpenAPI",
        resource: "openapi-task",
        operation: "write",
        command: "dida openapi task update <task-id> --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/task/{taskId}"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.taskComplete",
        title: "Complete task through official OpenAPI",
        resource: "openapi-task",
        operation: "write",
        command: "dida openapi task complete --project <project-id> --task <task-id> --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/project/{projectId}/task/{taskId}/complete"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.taskDelete",
        title: "Delete task through official OpenAPI",
        resource: "openapi-task",
        operation: "delete",
        command: "dida openapi task delete --project <project-id> --task <task-id> --dry-run --yes --json",
        aliases: &[],
        http: &["DELETE /open/v1/project/{projectId}/task/{taskId}"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.taskMove",
        title: "Move tasks through official OpenAPI",
        resource: "openapi-task",
        operation: "write",
        command: "dida openapi task move --args-json '[...]' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/task/move"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.taskCompleted",
        title: "List completed tasks through official OpenAPI",
        resource: "openapi-task",
        operation: "read",
        command: "dida openapi task completed --args-json '{...}' --json",
        aliases: &[],
        http: &["POST /open/v1/task/completed"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.taskFilter",
        title: "Filter tasks through official OpenAPI",
        resource: "openapi-task",
        operation: "read",
        command: "dida openapi task filter --args-json '{...}' --json",
        aliases: &[],
        http: &["POST /open/v1/task/filter"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.focusGet",
        title: "Get focus record through official OpenAPI",
        resource: "openapi-focus",
        operation: "read",
        command: "dida openapi focus get <focus-id> --type 0 --json",
        aliases: &[],
        http: &["GET /open/v1/focus/{focusId}?type=0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.focusList",
        title: "List focus records through official OpenAPI",
        resource: "openapi-focus",
        operation: "read",
        command: "dida openapi focus list --from TIME --to TIME --type 1 --json",
        aliases: &[],
        http: &["GET /open/v1/focus?from=...&to=...&type=..."],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Requires an already saved OAuth access token. Time range above 30 days may be adjusted by the server.",
        ),
    },
    CommandSchema {
        id: "openapi.focusDelete",
        title: "Delete focus record through official OpenAPI",
        resource: "openapi-focus",
        operation: "delete",
        command: "dida openapi focus delete <focus-id> --type 0 --dry-run --yes --json",
        aliases: &[],
        http: &["DELETE /open/v1/focus/{focusId}?type=0"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.habitList",
        title: "List habits through official OpenAPI",
        resource: "openapi-habit",
        operation: "read",
        command: "dida openapi habit list --json",
        aliases: &[],
        http: &["GET /open/v1/habit"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.habitGet",
        title: "Get habit through official OpenAPI",
        resource: "openapi-habit",
        operation: "read",
        command: "dida openapi habit get <habit-id> --json",
        aliases: &[],
        http: &["GET /open/v1/habit/{habitId}"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.habitCreate",
        title: "Create habit through official OpenAPI",
        resource: "openapi-habit",
        operation: "write",
        command: "dida openapi habit create --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/habit"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.habitUpdate",
        title: "Update habit through official OpenAPI",
        resource: "openapi-habit",
        operation: "write",
        command: "dida openapi habit update <habit-id> --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/habit/{habitId}"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.habitCheckin",
        title: "Create or update habit check-in through official OpenAPI",
        resource: "openapi-habit",
        operation: "write",
        command: "dida openapi habit checkin <habit-id> --args-json '{...}' --dry-run --json",
        aliases: &[],
        http: &["POST /open/v1/habit/{habitId}/checkin"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "openapi.habitCheckins",
        title: "List habit check-ins through official OpenAPI",
        resource: "openapi-habit",
        operation: "read",
        command: "dida openapi habit checkins --habit-ids h1,h2 --from YYYYMMDD --to YYYYMMDD --json",
        aliases: &[],
        http: &["GET /open/v1/habit/checkins?habitIds=...&from=...&to=..."],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Requires an already saved OAuth access token."),
    },
    CommandSchema {
        id: "agent.context",
        title: "One-call compact context pack",
        resource: "agent",
        operation: "read",
        command: "dida agent context --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "Returns projects, folders, tags, filters, today, upcoming, and quadrants from one sync. Use --outline for task id references plus a deduplicated taskIndex.",
        ),
    },
    CommandSchema {
        id: "sync.all",
        title: "Full account sync",
        resource: "sync",
        operation: "read",
        command: "dida sync all --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "sync.checkpoint",
        title: "Incremental account sync",
        resource: "sync",
        operation: "read",
        command: "dida sync checkpoint <checkpoint> --json",
        aliases: &[],
        http: &["GET /batch/check/{checkpoint}"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Preserves add/update/delete/order/reminder deltas."),
    },
    CommandSchema {
        id: "settings.get",
        title: "Read user settings",
        resource: "settings",
        operation: "read",
        command: "dida settings get --json",
        aliases: &[],
        http: &[
            "GET /user/preferences/settings",
            "GET /user/preferences/settings?includeWeb=true",
        ],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Use --include-web to include Web-side preference fields such as smartProjects and shortcut config.",
        ),
    },
    CommandSchema {
        id: "project.list",
        title: "List projects",
        resource: "project",
        operation: "read",
        command: "dida project list --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "project.tasks",
        title: "List tasks in a project",
        resource: "project",
        operation: "read",
        command: "dida project tasks <project-id> --limit 50 --compact --json",
        aliases: &[],
        http: &["GET /project/{projectId}/tasks"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: None,
    },
    CommandSchema {
        id: "project.create",
        title: "Create project",
        resource: "project",
        operation: "write",
        command: "dida project create --name <name> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/project"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "project.update",
        title: "Update project",
        resource: "project",
        operation: "write",
        command: "dida project update <project-id> --name <name> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/project"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "project.delete",
        title: "Delete project",
        resource: "project",
        operation: "delete",
        command: "dida project delete <project-id> --dry-run --yes --json",
        aliases: &[],
        http: &["POST /batch/project"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "folder.list",
        title: "List project folders",
        resource: "folder",
        operation: "read",
        command: "dida folder list --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "folder.create",
        title: "Create project folder",
        resource: "folder",
        operation: "write",
        command: "dida folder create --name <name> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/projectGroup"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "folder.update",
        title: "Update project folder",
        resource: "folder",
        operation: "write",
        command: "dida folder update <folder-id> --name <name> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/projectGroup"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "folder.delete",
        title: "Delete project folder",
        resource: "folder",
        operation: "delete",
        command: "dida folder delete <folder-id> --dry-run --yes --json",
        aliases: &[],
        http: &["POST /batch/projectGroup"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "tag.list",
        title: "List tags",
        resource: "tag",
        operation: "read",
        command: "dida tag list --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "tag.create",
        title: "Create tag",
        resource: "tag",
        operation: "write",
        command: "dida tag create <name> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/tag"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "tag.update",
        title: "Update tag metadata",
        resource: "tag",
        operation: "write",
        command: "dida tag update <name> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/tag"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "tag.rename",
        title: "Rename tag",
        resource: "tag",
        operation: "write",
        command: "dida tag rename <old-name> <new-name> --dry-run --json",
        aliases: &[],
        http: &["PUT /tag/rename"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "tag.merge",
        title: "Merge tag associations",
        resource: "tag",
        operation: "write",
        command: "dida tag merge <from-name> <to-name> --dry-run --yes --json",
        aliases: &[],
        http: &["PUT /tag/merge"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: Some(
            "Observed endpoint may leave the source tag object present; list tags after merge.",
        ),
    },
    CommandSchema {
        id: "tag.delete",
        title: "Delete tag",
        resource: "tag",
        operation: "delete",
        command: "dida tag delete <name> --dry-run --yes --json",
        aliases: &[],
        http: &["DELETE /tag?name=..."],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "filter.list",
        title: "List filters from sync payload",
        resource: "filter",
        operation: "read",
        command: "dida filter list --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "column.list",
        title: "List kanban columns",
        resource: "column",
        operation: "read",
        command: "dida column list <project-id> --json",
        aliases: &["dida project columns <project-id> --json"],
        http: &["GET /column/project/{projectId}"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "column.create",
        title: "Create kanban column",
        resource: "column",
        operation: "write",
        command: "dida column create --project <project-id> --name <name> --dry-run --json",
        aliases: &[],
        http: &["POST /column"],
        status: "experimental",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Update/delete/order remain blocked until /batch/columnProject payloads are verified.",
        ),
    },
    CommandSchema {
        id: "task.today",
        title: "List today's tasks",
        resource: "task",
        operation: "read",
        command: "dida task today --compact --json",
        aliases: &["dida +today --compact --json"],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: None,
    },
    CommandSchema {
        id: "task.list",
        title: "List active tasks",
        resource: "task",
        operation: "read",
        command: "dida task list --filter all --limit 50 --compact --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: None,
    },
    CommandSchema {
        id: "task.search",
        title: "Search tasks locally from sync",
        resource: "task",
        operation: "read",
        command: "dida task search --query <text> --limit 20 --compact --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: None,
    },
    CommandSchema {
        id: "task.upcoming",
        title: "List upcoming tasks",
        resource: "task",
        operation: "read",
        command: "dida task upcoming --days 14 --limit 50 --compact --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: None,
    },
    CommandSchema {
        id: "task.dueCounts",
        title: "Read due-date activity counts",
        resource: "task",
        operation: "read",
        command: "dida task due-counts --json",
        aliases: &[],
        http: &["POST /task/activity/count/all"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "POST read observed in the webapp bundle with action T_DUE; does not mutate tasks.",
        ),
    },
    CommandSchema {
        id: "task.create",
        title: "Create task",
        resource: "task",
        operation: "write",
        command: "dida task create --project <project-id> --title <title> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/task"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "task.update",
        title: "Update task",
        resource: "task",
        operation: "write",
        command: "dida task update <task-id> --project <project-id> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/task"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "task.complete",
        title: "Complete task",
        resource: "task",
        operation: "write",
        command: "dida task complete <task-id> --project <project-id> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/task"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "task.delete",
        title: "Delete task",
        resource: "task",
        operation: "delete",
        command: "dida task delete <task-id> --project <project-id> --dry-run --yes --json",
        aliases: &[],
        http: &["POST /batch/task"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "task.move",
        title: "Move task between projects",
        resource: "task",
        operation: "write",
        command: "dida task move <task-id> --from <project-id> --to <project-id> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/taskProject"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "task.parent",
        title: "Set task parent",
        resource: "task",
        operation: "write",
        command: "dida task parent <task-id> --parent <task-id> --project <project-id> --dry-run --json",
        aliases: &[],
        http: &["POST /batch/taskParent"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "comment.list",
        title: "List task comments",
        resource: "comment",
        operation: "read",
        command: "dida comment list --project <project-id> --task <task-id> --json",
        aliases: &[],
        http: &["GET /project/{projectId}/task/{taskId}/comments"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "comment.create",
        title: "Create task comment",
        resource: "comment",
        operation: "write",
        command: "dida comment create --project <project-id> --task <task-id> --text <text> --dry-run --json",
        aliases: &[],
        http: &["POST /project/{projectId}/task/{taskId}/comment"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "comment.createWithFile",
        title: "Create task comment with uploaded attachment",
        resource: "comment",
        operation: "write",
        command: "dida comment create --project <project-id> --task <task-id> --text <text> --file <path> --dry-run --json",
        aliases: &[],
        http: &[
            "POST /api/v1/attachment/upload/comment/{projectId}/{taskId}",
            "POST /project/{projectId}/task/{taskId}/comment",
        ],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Uses multipart field file, then sends comment attachments [{id}]. Use the real project id, not logical inbox.",
        ),
    },
    CommandSchema {
        id: "comment.update",
        title: "Update task comment",
        resource: "comment",
        operation: "write",
        command: "dida comment update --project <project-id> --task <task-id> --comment <comment-id> --text <text> --dry-run --json",
        aliases: &[],
        http: &["PUT /project/{projectId}/task/{taskId}/comment/{commentId}"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "comment.delete",
        title: "Delete task comment",
        resource: "comment",
        operation: "delete",
        command: "dida comment delete --project <project-id> --task <task-id> --comment <comment-id> --dry-run --yes --json",
        aliases: &[],
        http: &["DELETE /project/{projectId}/task/{taskId}/comment/{commentId}"],
        status: "stable",
        auth_required: true,
        dry_run: true,
        confirmation_required: true,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "completed.list",
        title: "List completed tasks",
        resource: "completed",
        operation: "read",
        command: "dida completed list --from YYYY-MM-DD --to YYYY-MM-DD --compact --json",
        aliases: &[],
        http: &["GET /project/all/completed"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: None,
    },
    CommandSchema {
        id: "closed.list",
        title: "List closed-history items",
        resource: "closed",
        operation: "read",
        command: "dida closed list --status 2 --limit 50 --json",
        aliases: &[],
        http: &["GET /project/{projectIds|all}/closed?from=...&to=...&status=..."],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Uses the private closed-history endpoint. Dates are sent as full datetime strings.",
        ),
    },
    CommandSchema {
        id: "trash.list",
        title: "List deleted tasks from trash",
        resource: "trash",
        operation: "read",
        command: "dida trash list --cursor 20 --compact --json",
        aliases: &[],
        http: &[
            "GET /project/all/trash/page",
            "GET /project/all/trash/page?from=<cursor>",
        ],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "The server returns next as the follow-up cursor. Avoid type=task; it returned HTTP 500 in live probing.",
        ),
    },
    CommandSchema {
        id: "attachment.quota",
        title: "Read attachment upload quota",
        resource: "attachment",
        operation: "read",
        command: "dida attachment quota --json",
        aliases: &[],
        http: &[
            "GET /api/v1/attachment/isUnderQuota",
            "GET /api/v1/attachment/dailyLimit",
        ],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Uses the legacy v1 Web API client observed as _s in the webapp bundle."),
    },
    CommandSchema {
        id: "reminder.daily",
        title: "Read daily reminder preferences",
        resource: "reminder",
        operation: "read",
        command: "dida reminder daily --json",
        aliases: &[],
        http: &["GET /user/preferences/dailyReminder"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "share.contacts",
        title: "Read share contacts",
        resource: "share",
        operation: "read",
        command: "dida share contacts --json",
        aliases: &[],
        http: &["GET /share/shareContacts"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "share.recentUsers",
        title: "Read recent project users",
        resource: "share",
        operation: "read",
        command: "dida share recent-users --json",
        aliases: &[],
        http: &["GET /project/share/recentProjectUsers"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "share.projectShares",
        title: "Read project sharing members",
        resource: "share",
        operation: "read",
        command: "dida share project shares <project-id> --json",
        aliases: &[],
        http: &["GET /project/{projectId}/shares"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "share.projectQuota",
        title: "Read project share quota",
        resource: "share",
        operation: "read",
        command: "dida share project quota <project-id> --json",
        aliases: &[],
        http: &["GET /project/{projectId}/share/check-quota"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "share.projectInviteURL",
        title: "Read project invite URL state",
        resource: "share",
        operation: "read",
        command: "dida share project invite-url <project-id> --json",
        aliases: &[],
        http: &["GET /project/{projectId}/collaboration/invite-url"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Read-only; invite creation/deletion writes remain intentionally unavailable."),
    },
    CommandSchema {
        id: "calendar.subscriptions",
        title: "Read calendar subscriptions",
        resource: "calendar",
        operation: "read",
        command: "dida calendar subscriptions --json",
        aliases: &[],
        http: &["GET /calendar/subscription"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "calendar.archived",
        title: "Read archived calendar events",
        resource: "calendar",
        operation: "read",
        command: "dida calendar archived --json",
        aliases: &[],
        http: &["GET /calendar/archivedEvent"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "calendar.thirdAccounts",
        title: "Read third-party calendar accounts",
        resource: "calendar",
        operation: "read",
        command: "dida calendar third-accounts --json",
        aliases: &[],
        http: &["GET /calendar/third/accounts"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("May expose connected account metadata; use only when needed."),
    },
    CommandSchema {
        id: "stats.general",
        title: "Read general account statistics",
        resource: "stats",
        operation: "read",
        command: "dida stats general --json",
        aliases: &[],
        http: &["GET /statistics/general"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "template.projectList",
        title: "List project templates",
        resource: "template",
        operation: "read",
        command: "dida template project list --limit 50 --json",
        aliases: &[],
        http: &["GET /projectTemplates/all?timestamp=..."],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "search.all",
        title: "Search indexed tasks and comments",
        resource: "search",
        operation: "read",
        command: "dida search all --query <text> --limit 20 --json",
        aliases: &[],
        http: &["GET /search/all?keywords=..."],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "The observed working query parameter is keywords; output is compact and bounded by default; use --full for raw search objects.",
        ),
    },
    CommandSchema {
        id: "user.status",
        title: "Read account status",
        resource: "user",
        operation: "read",
        command: "dida user status --json",
        aliases: &[],
        http: &["GET /user/status"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "Default output is compact; use --full only when raw account metadata is required.",
        ),
    },
    CommandSchema {
        id: "user.profile",
        title: "Read account profile",
        resource: "user",
        operation: "read",
        command: "dida user profile --json",
        aliases: &[],
        http: &["GET /user/profile"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "Default output is compact; use --full only when raw profile metadata is required.",
        ),
    },
    CommandSchema {
        id: "user.sessions",
        title: "Read login sessions",
        resource: "user",
        operation: "read",
        command: "dida user sessions --limit 20 --json",
        aliases: &[],
        http: &["GET /user/sessions?lang=..."],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: true,
        notes: Some(
            "Default output is compact; use --full only when raw session metadata is required.",
        ),
    },
    CommandSchema {
        id: "pomo.preferences",
        title: "Read Pomodoro preferences",
        resource: "pomo",
        operation: "read",
        command: "dida pomo preferences --json",
        aliases: &[],
        http: &["GET /user/preferences/pomodoro"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "pomo.list",
        title: "List Pomodoro records",
        resource: "pomo",
        operation: "read",
        command: "dida pomo list --from YYYY-MM-DD --to YYYY-MM-DD --limit 50 --json",
        aliases: &[],
        http: &["GET /pomodoros?from=<millis>&to=<millis>"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "pomo.timing",
        title: "List Pomodoro timing records",
        resource: "pomo",
        operation: "read",
        command: "dida pomo timing --from YYYY-MM-DD --to YYYY-MM-DD --limit 50 --json",
        aliases: &[],
        http: &["GET /pomodoros/timing?from=<millis>&to=<millis>"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "pomo.stats",
        title: "Read Pomodoro statistics",
        resource: "pomo",
        operation: "read",
        command: "dida pomo stats --json",
        aliases: &[],
        http: &["GET /pomodoros/statistics/generalForDesktop"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "pomo.timeline",
        title: "List Pomodoro timeline records",
        resource: "pomo",
        operation: "read",
        command: "dida pomo timeline --limit 50 --json",
        aliases: &[],
        http: &["GET /pomodoros/timeline"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "pomo.task",
        title: "List Pomodoro records for a task",
        resource: "pomo",
        operation: "read",
        command: "dida pomo task --project <project-id> --task <task-id> --json",
        aliases: &[],
        http: &["GET /pomodoros/task?projectId=...&taskId=..."],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "habit.preferences",
        title: "Read habit preferences",
        resource: "habit",
        operation: "read",
        command: "dida habit preferences --json",
        aliases: &[],
        http: &["GET /user/preferences/habit?platform=web"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "habit.list",
        title: "List habits",
        resource: "habit",
        operation: "read",
        command: "dida habit list --json",
        aliases: &[],
        http: &["GET /habits"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "habit.sections",
        title: "List habit sections",
        resource: "habit",
        operation: "read",
        command: "dida habit sections --json",
        aliases: &[],
        http: &["GET /habitSections"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "habit.checkins",
        title: "Read habit check-ins",
        resource: "habit",
        operation: "read",
        command: "dida habit checkins --habit <habit-id> --after-stamp <millis> --json",
        aliases: &[],
        http: &["POST /habitCheckins/query"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("POST read; accepts repeated --habit and optional afterStamp cursor."),
    },
    CommandSchema {
        id: "quadrant.list",
        title: "Group active tasks into Eisenhower quadrants",
        resource: "quadrant",
        operation: "read",
        command: "dida quadrant list --json",
        aliases: &[],
        http: &["GET /batch/check/0"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: None,
    },
    CommandSchema {
        id: "raw.get",
        title: "Read-only raw Web API probe",
        resource: "raw",
        operation: "read",
        command: "dida raw get /path --api-version v1|v2 --json",
        aliases: &[],
        http: &["GET <path>"],
        status: "stable",
        auth_required: true,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some("Raw writes are intentionally unavailable."),
    },
    CommandSchema {
        id: "upgrade",
        title: "Self-update CLI binary",
        resource: "system",
        operation: "write",
        command: "dida upgrade --json",
        aliases: &[],
        http: &[],
        status: "stable",
        auth_required: false,
        dry_run: false,
        confirmation_required: false,
        compact: false,
        notes: Some(
            "Queries GitHub Releases, verifies SHA-256 checksum, and installs the matched binary. Windows schedules replacement after the current process exits. Use --check for version check only.",
        ),
    },
];

pub fn filtered_schemas(options: ListOptions<'_>) -> Vec<&'static CommandSchema> {
    COMMAND_SCHEMAS
        .iter()
        .filter(|schema| {
            options
                .resource
                .is_none_or(|resource| schema.resource == resource)
                && options
                    .operation
                    .is_none_or(|operation| schema.operation == operation)
                && options.status.is_none_or(|status| schema.status == status)
        })
        .collect()
}

pub fn find_schema(id: &str) -> Option<&'static CommandSchema> {
    COMMAND_SCHEMAS.iter().find(|schema| schema.id == id)
}

pub fn list_json(options: ListOptions<'_>) -> String {
    let schemas = filtered_schemas(options);
    let mut out = String::from(r#"{"ok":true,"command":"schema list","meta":{"compact":"#);
    out.push_str(bool_json(options.compact));
    out.push_str(r#","count":"#);
    out.push_str(&schemas.len().to_string());
    if let Some(operation) = options.operation {
        out.push_str(r#","operation":"#);
        push_json_string(&mut out, operation);
    }
    if let Some(resource) = options.resource {
        out.push_str(r#","resource":"#);
        push_json_string(&mut out, resource);
    }
    if let Some(status) = options.status {
        out.push_str(r#","status":"#);
        push_json_string(&mut out, status);
    }
    out.push_str(r#"},"data":{"schemas":["#);
    for (index, schema) in schemas.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        if options.compact {
            push_compact_schema(&mut out, schema);
        } else {
            push_full_schema(&mut out, schema);
        }
    }
    out.push_str(r#"]}}"#);
    out.push('\n');
    out
}

pub fn show_json(schema: &CommandSchema) -> String {
    let mut out = String::from(r#"{"ok":true,"command":"schema show","data":{"schema":"#);
    push_full_schema(&mut out, schema);
    out.push_str(r#"}}"#);
    out.push('\n');
    out
}

fn push_compact_schema(out: &mut String, schema: &CommandSchema) {
    out.push('{');
    push_field(out, "id", schema.id);
    out.push(',');
    push_field(out, "resource", schema.resource);
    out.push(',');
    push_field(out, "operation", schema.operation);
    out.push(',');
    push_field(out, "command", schema.command);
    out.push(',');
    push_field(out, "status", schema.status);
    out.push(',');
    out.push_str(r#""authRequired":"#);
    out.push_str(bool_json(schema.auth_required));
    out.push_str(r#","dryRun":"#);
    out.push_str(bool_json(schema.dry_run));
    out.push_str(r#","confirmationRequired":"#);
    out.push_str(bool_json(schema.confirmation_required));
    out.push_str(r#","compact":"#);
    out.push_str(bool_json(schema.compact));
    out.push('}');
}

fn push_full_schema(out: &mut String, schema: &CommandSchema) {
    out.push('{');
    push_field(out, "id", schema.id);
    out.push(',');
    push_field(out, "title", schema.title);
    out.push(',');
    push_field(out, "resource", schema.resource);
    out.push(',');
    push_field(out, "operation", schema.operation);
    out.push(',');
    push_field(out, "command", schema.command);
    out.push(',');
    if !schema.aliases.is_empty() {
        out.push_str(r#""aliases":"#);
        push_string_array(out, schema.aliases);
        out.push(',');
    }
    if !schema.http.is_empty() {
        out.push_str(r#""http":"#);
        push_string_array(out, schema.http);
        out.push(',');
    }
    push_field(out, "status", schema.status);
    out.push_str(r#","authRequired":"#);
    out.push_str(bool_json(schema.auth_required));
    out.push_str(r#","dryRun":"#);
    out.push_str(bool_json(schema.dry_run));
    out.push_str(r#","confirmationRequired":"#);
    out.push_str(bool_json(schema.confirmation_required));
    out.push_str(r#","compact":"#);
    out.push_str(bool_json(schema.compact));
    if let Some(notes) = schema.notes {
        out.push_str(r#","notes":"#);
        push_json_string(out, notes);
    }
    out.push('}');
}

fn push_field(out: &mut String, name: &str, value: &str) {
    out.push('"');
    out.push_str(name);
    out.push_str("\":");
    push_json_string(out, value);
}

fn push_string_array(out: &mut String, values: &[&str]) {
    out.push('[');
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        push_json_string(out, value);
    }
    out.push(']');
}

fn push_json_string(out: &mut String, value: &str) {
    out.push_str(&serde_json::to_string(value).expect("schema string encodes"));
}

fn bool_json(value: bool) -> &'static str {
    if value { "true" } else { "false" }
}
